#!/bin/sh

compile_typespec \
	-impl Bio::KBase::GenomeAnnotation::%sImpl \
	-service Bio::KBase::GenomeAnnotation::Service \
	-psgi GenomeAnnotation.psgi \
	-client Bio::KBase::GenomeAnnotation::Client \
	-js GenomeAnnotation \
	-py GenomeAnnotation \
	-url https://kbase.us/services/genome_annotation \
	GenomeAnnotation.spec lib
